table Orders
	lineageTag: 20b32a1f-6b74-475e-850b-5f74d91fefc8

	measure 'Total Sales' = SUM(Orders[Sales])
		lineageTag: bacd8b5f-5e74-44aa-b21f-b4a2050fb632

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(Orders[Profit])
		lineageTag: d84076fd-a335-4a91-a680-539005bf1582

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 80d1d0ef-5e8f-4b9d-880f-d49644740f83
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 512ac155-6115-4326-8573-48201ea0b674
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1eb26d47-f939-4962-ada3-a5d093dc9303
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: c88ea5ae-9ee6-4429-b48a-1b9303c35723
			defaultHierarchy: LocalDateTable_564f0b31-e0c9-450c-97f7-85f321722ebb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 21ee455f-0030-46cc-b133-025bee157dc6
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 8a95d23b-429e-400f-a7a8-505c1602f745
			defaultHierarchy: LocalDateTable_7be961b8-12af-43bd-bd2b-7c9b96d94e0a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: a4f08d9a-5ffb-4528-8375-98603203cab7
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 74a1a020-6b96-4245-a0d8-d4d4d40de94c
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 3be6f922-18cf-4f4d-9f58-e22b3273c75e
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 04c68a04-5107-4ff1-b80f-37c11395c76c
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: cb2a1c13-b9c7-42d6-8d8f-066e6bd187f4
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: c12c99b5-fab3-4db8-bc5d-bdfa1adf3ea3
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: c8607c7f-210b-4539-b004-b87f7a7bccac
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: f3ef621a-f558-452c-9ddf-35b562a79909
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2cef80b0-a133-4e2f-a904-ad42231f4f7b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: e175b491-53e1-4428-a714-4b6ba79cff6e
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d9af56d3-5bd1-42c4-9804-29b3ca20a8f7
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: bda4467b-9faa-4316-ace6-c72598fe0649
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: c0a28d32-6a06-46cd-ad28-b1542ffff5c4
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 23eaa185-b7e4-4f51-ab2b-93121544dc44
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 0e1dcec1-8317-456a-b4f0-069909852f59
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 8202247c-8286-4bbb-b5c9-701627d6433a
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: a1128e31-c32c-488c-9867-9fe1860c0f58
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Docker\Downloads\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

